export enum WireTransferType {
    FIRST_DEPOSIT_FOR_ACCOUNT_OPENNING = 'FIRST_DEPOSIT_FOR_ACCOUNT_OPENNING',
    DEPOSIT = 'DEPOSIT',
    WITHDRAWAL = 'WITHDRAWAL',
    TRANSFER = 'TRANSFER'
}

export enum BankAccountType {
    SAVINGS = 'SAVINGS',
    CHECKING = 'CHECKING'
}